### ISSUE TITLE
[Question] Generate mesh from voxels and smooth with haze

### ISSUE THREAD

**Issue by dipterix** [dfsp-spirit/haze#2]
Hi @dfsp-spirit , this is an amazing work! I was wondering if there's any method that can directly generate meshes from voxel locations (without freesurfer), and then smooth via `haze`?

**Comment by dfsp-spirit** [comment]
Hi dipterix,

To generate a mesh from voxels with FreeSurfer command line tools, `mri_tesselate` is maybe what you want. 

But once you have the mesh, do you want to smooth _the mesh itself_ or _per-vertex data for the mesh_? I guess you read this on the haze page:

    What haze is not
    To avoid any confusion: haze does not smooth the mesh itself, use [Rvcg](https://github.com/zarquon42b/Rvcg)::vcgSmooth() for that.

**Comment by dfsp-spirit** [comment]
To generate a mesh from voxels with FreeSurfer command line tools, `mri_tesselate` is maybe what you want. 

But once you have the mesh, do you want to smooth _the mesh itself_ or _per-vertex data for the mesh_? I guess you read this on the haze page:

    What haze is not
    To avoid any confusion: haze does not smooth the mesh itself, use [Rvcg](https://github.com/zarquon42b/Rvcg)::vcgSmooth() for that.

**Comment by dfsp-spirit** [comment]
Update: Oh sorry, I misread `without FreeSurfer` for `with FreeSurfer` in my first answer. Then yes, what you want is `misc3d::countour3d()`.

**Comment by dipterix** [comment]
I see, so haze does data smoothing while Rvcg smooths the mesh

**Comment by dfsp-spirit** [comment]
Exactly.
